---
- name: Manage contexts or VRFs (fvCTX)
  aci_vrf:
    hostname: '{{ apic_ip }}'
    username: '{{ apic_username }}'
    password: '{{ apic_password }}'
    validate_certs: no
    tenant: "{{ item.tenant_name }}"
    vrf_name: "{{ item.tenant_vrf_name }}"
    state: "{{ item.tenant_vrf_state }}"
  with_items:
    - "{{ ACI_Fabric|aci_listify('tenant','vrf') }}"
