---
- name: Create Interface Profile
  hosts: "{{ target }}"
  gather_facts: no

  tasks:
    - include_vars:
        file: "{{ ACI_Env_Path }}/fabric.yml"
        name: ACI_Fabric

    - include_role:
         name: aci-interface-profile      # Create Interface Profile for Access Port or PC/vPC
