- name: Bind a Domain to VLAN Pools (infra:RsVlanNs)
  aci_domain_to_vlan_pool:
    host: '{{ apic_ip }}'
    username: '{{ apic_username }}'
    password: '{{ apic_password }}'
    validate_certs: no
    domain: "{{ item.access_policy_physical_domain_name }}"
    domain_type: phys
    pool: "{{ item.access_policy_physical_domain_vlan_pool }}"
    state: "{{ item.access_policy_physical_domain_state }}"
    pool_allocation_mode: "{{ item.access_policy_physical_domain_vlan_pool_alloc }}"
  with_items: '{{ ACI_Fabric|aci_listify("access_policy","physical_domain") }}'
